add_newline = false

[character]
symbol = "$"

[package]
disabled = true

[cmd_duration]
disabled = true

[line_break]
disabled = false

[ruby]
disabled = true

[nodejs]
disabled = true

[python]
symbol = "python: "

[rust]
symbol = "rust: "
