add_newline = false

[character]
symbol = "$"

[package]
disabled = true

[cmd_duration]
disabled = true

[line_break]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true
