name: CI
on: [push]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run setup.sh
      run: ./script/install.sh
    - name: Execute cargo make
      run: cargo make --makefile script/setup.toml setup

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run setup.sh
      run: ./script/install.sh
    - name: Execute cargo make
      run: cargo make --makefile script/setup.toml setup
